import type { Meta, StoryObj } from '@storybook/react';
import TourneyCard from './TourneyCard';

const meta = {
  title: 'Design System/TourneyCard',
  component: TourneyCard,
  tags: ['autodocs'],
  parameters: {
    // More on how to position stories at: https://storybook.js.org/docs/react/configure/story-layout
  },
} satisfies Meta<typeof TourneyCard>;

export default meta;
type Story = StoryObj<typeof TourneyCard>;

export const Example1: Story = {
  args: {
    tourney: {
      "TournamentID": "aad5cd4c-b752-4642-9d50-666f352a9228",
      "ClubID": "51e3befa-85f0-46c5-b776-7a7d5241fc37",
      "Platform": "PickleballBrackets",
      "DetailsURL": "https://pickleballbrackets.com/ptd.aspx?eid=AAD5CD4C-B752-4642-9D50-666F352A9228",
      "CancelTourney": false,
      "CostFeeOnEvents": true,
      "CostRegistrationCurrent": 80,
      "TourneyFromDate": new Date("2023-01-03T14:00:00Z"),
      "TourneyToDate": new Date("2024-12-03T14:00:00Z"),
      "IsPrizeMoney": true,
      "IsRegClosed": false,
      "LocationCity": "Westfield",
      "LocationCountry": "USA",
      "LocationState": "IN",
      "LocationStreetAddress": "19000 Grand Park Blve",
      "LocationVenue": "Grand Park Sports Campus",
      "LocationZip": "46074",
      "Logo": "https://images.pickleball.com/placeholder/pickleball.png",
      "OnlineRegistrationActive": true,
      "RegistrationCount": 0,
      "RegistrationDateClosed": new Date("2023-12-24T05:55:00Z"),
      "RegistrationDateOpen": new Date("2023-09-19T16:00:00Z"),
      "TimeZoneAbbreviation": "CDT",
      "Title": "APP U.S. Collegiate Championships and Midwest Open",
      "IsFeatured": false,
      "Longitude": -86.150055,
      "Latitude": 40.06326,
      "FormatCode": "en-US",
      "TimeZoneUTCOffset": -18000,
      "IsFeaturedPlus": false,
      "ContactFormRegistration": "app.collegiate@outlook.com",
      "ContactFormMyWebsiteAccount": "app.collegiate@outlook.com",
      "ContactFormRefunds": "app.collegiate@outlook.com",
      "ContactFormOther": "app.collegiate@outlook.com",
      "ContactFormRequestPartnerChange": "app.collegiate@outlook.com",
      "ContactFormVolunteer": "ladym@mindspring.com",
      "ContactFormReferee": "ladym@mindspring.com",
      "ContactFormVendor": "jradin@intersportnet.com",
      "ContactFormSponsor": "jradin@intersportnet.com",
      "ContactFormPublicDisplayName": "Dana Joseph",
      "ContactFormPublicDisplayEmail": "app.collegiate@outlook.com",
      "ContactFormPublicDisplayPhone": "847-404-3174",
      "DateArchived": undefined,
      "DateShowToPublic": new Date("2023-09-14T19:00:00Z"),
      "DateHideFromPublic": undefined,
      "GoverningBodies": [],
      "PBTournamentCode": "PB3863",
      "IsTest": false,
      "IsAdvertiseOnly": false,
      "DateCompleted": undefined,
      "UsingGeniusSports": false,
      "ClubSanctionLevelId": "",
      "dateCreated": new Date("2023-09-12T14:31:51.141Z"),
      "dateUpdated": new Date("2023-09-12T15:21:54.666Z"),
      "hideRegisteredPlayers": false,
      "hideTourneyOnSearchPage": false,
      "lockDate": undefined,
      //"tierLevelUuid": "",
      //"ticketsUrl": ""
    }
  }
};

export const Example2: Story = {
  args: {
    tourney: {
      "TournamentID": "e0091d55-b4f3-4839-a35a-52aac58501aa",
      "ClubID": "a49282ef-fde5-4adb-a81f-acf643bdec58",
      "Platform": "PickleballBrackets",
      "DetailsURL": "https://pickleballbrackets.com/ptd.aspx?eid=E0091D55-B4F3-4839-A35A-52AAC58501AA",
      "CancelTourney": false,
      "CostFeeOnEvents": true,
      "CostRegistrationCurrent": 45,
      "TourneyFromDate": new Date("2023-06-10T00:00:00Z"),
      "TourneyToDate": new Date("2024-06-26T02:30:00Z"),
      "IsPrizeMoney": false,
      "IsRegClosed": false,
      "LocationCity": "Kingston",
      "LocationCountry": "AUS",
      "LocationState": "Tas",
      "LocationStreetAddress": "Kingborough Sports Centre",
      "LocationVenue": "Kingborough Sports Centre",
      "LocationZip": "7050",
      "Logo": "https://pickleballbrackets.com/uploads/events/E0091D55-B4F3-4839-A35A-52AAC58501AA/Clubs/a49282ef-fde5-4adb-a81f-acf643bdec58/e0091d55-b4f3-4839-a35a-52aac58501aa_Logo.png",
      "OnlineRegistrationActive": false,
      "RegistrationCount": 0,
      "RegistrationDateClosed": new Date("2023-05-25T07:00:00Z"),
      "RegistrationDateOpen": new Date("2023-03-25T22:00:00Z"),
      "TimeZoneAbbreviation": "AEST",
      "Title": "Sponsor 2023 Pickleball Tasmania Open",
      "IsFeatured": false,
      "Longitude": 147.28644,
      "Latitude": -42.971558,
      "FormatCode": "en-AU",
      "TimeZoneUTCOffset": 10,
      "IsFeaturedPlus": false,
      "ContactFormRegistration": "glenn675@gmail.com",
      "ContactFormMyWebsiteAccount": "glenn675@gmail.com",
      "ContactFormRefunds": "treasurer@pickleballtasmania.org",
      "ContactFormOther": "glenn675@gmail.com",
      "ContactFormRequestPartnerChange": "glenn675@gmail.com",
      "ContactFormVolunteer": "glenn675@gmail.com",
      "ContactFormReferee": "glenn675@gmail.com",
      "ContactFormVendor": "vicepresident@pickleballtasmania.org",
      "ContactFormSponsor": "vicepresident@pickleballtasmania.org",
      "ContactFormPublicDisplayName": "Glenn Wheeler",
      "ContactFormPublicDisplayEmail": "glenn675@gmail.com",
      "ContactFormPublicDisplayPhone": "",
      "DateArchived": undefined,
      "DateShowToPublic": new Date("2023-03-25T12:00:00Z"),
      "DateHideFromPublic": undefined,
      "GoverningBodies": [
          {
              "id": 7,
              "approvedStatus": "Pending",
              "sanctionLevelId": "",
              "shortName": "PAA"
          }
      ],
      "PBTournamentCode": "PB2162",
      "IsTest": false,
      "IsAdvertiseOnly": false,
      "DateCompleted": undefined,
      "UsingGeniusSports": false,
      "ClubSanctionLevelId": "",
      "dateCreated": undefined,
      "dateUpdated": undefined,
      "hideRegisteredPlayers": false,
      "hideTourneyOnSearchPage": false,
      "lockDate": undefined,
      //"tierLevelUuid": "",
      //"ticketsUrl": ""
    }
  }
}

export const Example3: Story = {
  args: {
    tourney: {
      "TournamentID": "3d1c3667-6032-40ed-bbe0-7b3b94c4a664",
      "ClubID": "20183e58-f62b-412a-b913-a0543da4d4dd",
      "Platform": "PickleballBrackets",
      "DetailsURL": "https://pickleballbrackets.com/ptd.aspx?eid=3D1C3667-6032-40ED-BBE0-7B3B94C4A664",
      "CancelTourney": false,
      "CostFeeOnEvents": true,
      "CostRegistrationCurrent": 39,
      "TourneyFromDate": new Date("2023-06-23T23:00:00Z"),
      "TourneyToDate": new Date("2024-05-22T18:00:00Z"),
      "IsPrizeMoney": false,
      "IsRegClosed": false,
      "LocationCity": "North Conway",
      "LocationCountry": "USA",
      "LocationState": "NH",
      "LocationStreetAddress": "87 Fairway Drive",
      "LocationVenue": "White Mountain Hotel & Resort",
      "LocationZip": "03860",
      "Logo": "https://pickleballbrackets.com/uploads/events/3D1C3667-6032-40ED-BBE0-7B3B94C4A664/3d1c3667-6032-40ed-bbe0-7b3b94c4a664_Logo.png",
      "OnlineRegistrationActive": false,
      "RegistrationCount": 0,
      "RegistrationDateClosed": new Date("2023-06-01T04:55:00Z"),
      "RegistrationDateOpen": new Date("2023-02-06T13:00:00Z"),
      "TimeZoneAbbreviation": "EST",
      "Title": "White Mountain Hotel & Resort Pickleball Tournament 2023",
      "IsFeatured": false,
      "Longitude": -71.16471,
      "Latitude": 44.05404,
      "FormatCode": "en-US",
      "TimeZoneUTCOffset": -5,
      "IsFeaturedPlus": false,
      "ContactFormRegistration": "tsullivan@whitemountainhotel.com",
      "ContactFormMyWebsiteAccount": "tsullivan@whitemountainhotel.com",
      "ContactFormRefunds": "tsullivan@whitemountainhotel.com",
      "ContactFormOther": "tsullivan@whitemountainhotel.com",
      "ContactFormRequestPartnerChange": "tsullivan@whitemountainhotel.com",
      "ContactFormVolunteer": "tsullivan@whitemountainhotel.com",
      "ContactFormReferee": "tsullivan@whitemountainhotel.com",
      "ContactFormVendor": "tsullivan@whitemountainhotel.com",
      "ContactFormSponsor": "tsullivan@whitemountainhotel.com",
      "ContactFormPublicDisplayName": "Trevor Sullivan",
      "ContactFormPublicDisplayEmail": "tsullivan@whitemountainhotel.com",
      "ContactFormPublicDisplayPhone": "",
      "DateArchived": undefined,
      "DateShowToPublic": new Date("2023-01-31T04:00:00Z"),
      "DateHideFromPublic": undefined,
      "GoverningBodies": [],
      "PBTournamentCode": "PB1911",
      "IsTest": false,
      "IsAdvertiseOnly": false,
      "DateCompleted": undefined,
      "UsingGeniusSports": false,
      "ClubSanctionLevelId": "",
      "dateCreated": undefined,
      "dateUpdated": undefined,
      "hideRegisteredPlayers": false,
      "hideTourneyOnSearchPage": false,
      "lockDate": undefined,
      //"tierLevelUuid": "",
      //"ticketsUrl": ""
    }
  }
}

export const Example4: Story = {
  args: {
    tourney: {
      "TournamentID": "c2667232-7649-4adc-bcba-9ee6709abde9",
      "ClubID": "c3da765f-c804-48db-a702-bc1df6c8456c",
      "Platform": "PickleballBrackets",
      "DetailsURL": "https://pickleballbrackets.com/ptd.aspx?eid=C2667232-7649-4ADC-BCBA-9EE6709ABDE9",
      "CancelTourney": false,
      "CostFeeOnEvents": true,
      "CostRegistrationCurrent": 45,
      "TourneyFromDate": new Date("2023-08-05T00:30:00Z"),
      "TourneyToDate": new Date("2024-08-04T22:00:00Z"),
      "IsPrizeMoney": false,
      "IsRegClosed": true,
      "LocationCity": "Sterling",
      "LocationCountry": "USA",
      "LocationState": "VA",
      "LocationStreetAddress": "44610 Prentice Dr",
      "LocationVenue": "Life Time Loudon (Ashburn-Sterling)",
      "LocationZip": "20166",
      "Logo": "https://pickleballbrackets.com/uploads/Clubs/c3da765f-c804-48db-a702-bc1df6c8456c/c2667232-7649-4adc-bcba-9ee6709abde9_Logo.jpg",
      "OnlineRegistrationActive": true,
      "RegistrationCount": 89,
      "RegistrationDateClosed": new Date("2023-08-04T04:30:00Z"),
      "RegistrationDateOpen": new Date("2023-07-08T13:00:00Z"),
      "TimeZoneAbbreviation": "EST",
      "Title": "Summer Shade Tournament Life Time Loudoun  August 4th - August 6th, 2023",
      "IsFeatured": false,
      "Longitude": -77.45818,
      "Latitude": 39.003544,
      "FormatCode": "en-US",
      "TimeZoneUTCOffset": -18000,
      "IsFeaturedPlus": false,
      "ContactFormRegistration": "rhelgesen@lt.life",
      "ContactFormMyWebsiteAccount": "rhelgesen@lt.life",
      "ContactFormRefunds": "rhelgesen@lt.life",
      "ContactFormOther": "rhelgesen@lt.life",
      "ContactFormRequestPartnerChange": "rhelgesen@lt.life",
      "ContactFormVolunteer": "rhelgesen@lt.life",
      "ContactFormReferee": "rhelgesen@lt.life",
      "ContactFormVendor": "rhelgesen@lt.life",
      "ContactFormSponsor": "rhelgesen@lt.life",
      "ContactFormPublicDisplayName": "Rowena Helgesen",
      "ContactFormPublicDisplayEmail": "rhelgesen@lt.life",
      "ContactFormPublicDisplayPhone": "17034330256",
      "DateArchived": undefined,
      "DateShowToPublic": new Date("2023-07-08T17:00:00Z"),
      "DateHideFromPublic": undefined,
      "GoverningBodies": [],
      "PBTournamentCode": "PB3221",
      "IsTest": false,
      "IsAdvertiseOnly": false,
      "DateCompleted": undefined,
      "UsingGeniusSports": false,
      "ClubSanctionLevelId": "",
      "dateCreated": new Date("2023-07-07T03:49:57.594Z"),
      "dateUpdated": new Date("2023-08-14T14:21:28.825Z"),
      "hideRegisteredPlayers": false,
      "hideTourneyOnSearchPage": false,
      "lockDate": undefined,
      //"tierLevelUuid": "",
      //"ticketsUrl": ""
    }
  }
}

export const Example5: Story = {
  args: {
    tourney: {
      "TournamentID": "c1cad0d9-6c01-44b3-894c-ff4593e8d6f1",
      "ClubID": "dec3e8b9-a984-40e2-9079-34b589068724",
      "Platform": "PickleballBrackets",
      "DetailsURL": "https://pickleballbrackets.com/ptd.aspx?eid=C1CAD0D9-6C01-44B3-894C-FF4593E8D6F1",
      "CancelTourney": false,
      "CostFeeOnEvents": true,
      "CostRegistrationCurrent": 55,
      "TourneyFromDate": new Date("2023-08-12T13:00:00Z"),
      "TourneyToDate": new Date("2024-05-28T13:00:00Z"),
      "IsPrizeMoney": false,
      "IsRegClosed": false,
      "LocationCity": "Owings Mills",
      "LocationCountry": "USA",
      "LocationState": "MD",
      "LocationStreetAddress": "300 Garrison Forest Road",
      "LocationVenue": "Garrison Forest High School",
      "LocationZip": "21117",
      "Logo": "https://images.pickleball.com/placeholder/pickleball.png",
      "OnlineRegistrationActive": true,
      "RegistrationCount": 0,
      "RegistrationDateClosed": new Date("2024-08-06T13:00:00Z"),
      "RegistrationDateOpen": new Date("2024-06-01T16:30:00Z"),
      "TimeZoneAbbreviation": "EST",
      "Title": "Pickleball Tournament",
      "IsFeatured": false,
      "Longitude": -76.76366,
      "Latitude": 39.410526,
      "FormatCode": "en-US",
      "TimeZoneUTCOffset": -5,
      "IsFeaturedPlus": false,
      "ContactFormRegistration": "amecameron@hotmail.com",
      "ContactFormMyWebsiteAccount": "amecameron@hotmail.com",
      "ContactFormRefunds": "mike@picklemesilly.com",
      "ContactFormOther": "mike@picklemesilly.com",
      "ContactFormRequestPartnerChange": "amecameron@hotmail.com",
      "ContactFormVolunteer": "mike@picklemesilly.com",
      "ContactFormReferee": "mike@picklemesilly.com",
      "ContactFormVendor": "mike@picklemesilly.com",
      "ContactFormSponsor": "mike@picklemesilly.com",
      "ContactFormPublicDisplayName": "Amy Cameron",
      "ContactFormPublicDisplayEmail": "amecameron@hotmail.com",
      "ContactFormPublicDisplayPhone": "",
      "DateArchived": undefined,
      "DateShowToPublic": new Date("2023-05-19T17:00:00Z"),
      "DateHideFromPublic": undefined,
      "GoverningBodies": [],
      "PBTournamentCode": "PB2802",
      "IsTest": false,
      "IsAdvertiseOnly": false,
      "DateCompleted": undefined,
      "UsingGeniusSports": false,
      "ClubSanctionLevelId": "",
      "dateCreated": undefined,
      "dateUpdated": undefined,
      "hideRegisteredPlayers": false,
      "hideTourneyOnSearchPage": false,
      "lockDate": undefined,
      //"tierLevelUuid": "",
      //"ticketsUrl": ""
    }
  }
}

export const Example6: Story = {
  args: {
    tourney: {  
      "TournamentID": "5998d61a-552a-4413-b46f-9c727c276f9d",
      "ClubID": "51e3befa-85f0-46c5-b776-7a7d5241fc37",
      "Platform": "PickleballBrackets",
      "DetailsURL": "https://pickleballbrackets.com/ptd.aspx?eid=5998D61A-552A-4413-B46F-9C727C276F9D",
      "CancelTourney": false,
      "CostFeeOnEvents": true,
      "CostRegistrationCurrent": 80,
      "TourneyFromDate": new Date("2023-09-20T13:00:00Z"),
      "TourneyToDate": new Date("2023-10-01T13:00:00Z"),
      "IsPrizeMoney": true,
      "IsRegClosed": true,
      "LocationCity": "Griffin",
      "LocationCountry": "USA",
      "LocationState": "GA",
      "LocationStreetAddress": "1301 Cowan Road",
      "LocationVenue": "Spalding County Pickleball Complex",
      "LocationZip": "30223",
      "Logo": "https://pickleballbrackets.com/uploads/Clubs/51e3befa-85f0-46c5-b776-7a7d5241fc37/5998d61a-552a-4413-b46f-9c727c276f9d_Logo.jpg",
      "OnlineRegistrationActive": true,
      "RegistrationCount": 664,
      "RegistrationDateClosed": new Date("2023-09-18T04:55:00Z"),
      "RegistrationDateOpen": new Date("2023-06-08T22:00:00Z"),
      "TimeZoneAbbreviation": "EDT",
      "Title": "APP Sunmed Atlanta Open",
      "IsFeatured": false,
      "Longitude": -84.3087,
      "Latitude": 33.285316,
      "FormatCode": "en-US",
      "TimeZoneUTCOffset": -14400,
      "IsFeaturedPlus": false,
      "ContactFormRegistration": "APP.Atlanta23@outlook.com",
      "ContactFormMyWebsiteAccount": "APP.Atlanta23@outlook.com",
      "ContactFormRefunds": "APP.Atlanta23@outlook.com",
      "ContactFormOther": "APP.Atlanta23@outlook.com",
      "ContactFormRequestPartnerChange": "APP.Atlanta23@outlook.com",
      "ContactFormVolunteer": "llowryafs@gmail.com",
      "ContactFormReferee": "ladym@mindspring.com",
      "ContactFormVendor": "jradin@intersportnet.com",
      "ContactFormSponsor": "jradin@intersportnet.com",
      "ContactFormPublicDisplayName": "Dana Joseph",
      "ContactFormPublicDisplayEmail": "APP.Atlanta23@outlook.com",
      "ContactFormPublicDisplayPhone": "847-404-3174",
      "DateArchived": undefined,
      "DateShowToPublic": new Date("2023-06-06T21:00:00Z"),
      "DateHideFromPublic": undefined,
      "GoverningBodies": [
          {
              "id": 5,
              "approvedStatus": "Approved",
              "sanctionLevelId": "5a8722c5-ea02-455a-9f22-938b626723de",
              "shortName": "USAP"
          }
      ],
      "PBTournamentCode": "PB2785",
      "IsTest": false,
      "IsAdvertiseOnly": false,
      "DateCompleted": undefined,
      "UsingGeniusSports": false,
      "ClubSanctionLevelId": "",
      "dateCreated": undefined,
      "dateUpdated": new Date("2023-09-20T21:18:21.317Z"),
      "hideRegisteredPlayers": false,
      "hideTourneyOnSearchPage": false,
      "lockDate": undefined,
      //"tierLevelUuid": "",
      //"ticketsUrl": ""
    }
  }
}
